#!/usr/bin/env python

# Make HTTP request with authentication and verify it's allowed

import base64, os
from mail.test import *
from twisted.internet import protocol
from twisted.web import http

expect(1)

host = os.environ.get('LC_HOST', 'mail.nottheoilrig.com')

@sdfg
def _():

  @untwisted.call
  class factory(protocol.ClientFactory):
    class protocol(http.HTTPClient):
      def connectionMade(ctx):
        ctx.sendCommand('GET', '/bob@example.com')

        ctx.sendHeader('Authorization', 'Basic ' + base64.b64encode(username + ':' + password))

        ctx.endHeaders()

      def handleResponse(ctx, body):
        pass

      handleStatus = lambda ctx, version, code, phrase: equal('200', code)

  reactor.connectTCP(host, 'http', factory)

  return promise.promise()
