#!/usr/bin/env python

# Connect to IMAP server with wrong password and verify there's an error

import os
from mail.test import *
from twisted.internet import protocol
from twisted.mail import imap4

expect(1)

host = os.environ.get('LC_HOST', 'mail.nottheoilrig.com')

@sdfg
def _():

  @untwisted.call
  class factory(protocol.ClientFactory):
    class protocol(imap4.IMAP4Client):
      def serverGreeting(ctx, _):

        @untwisted.partial(ctx.authenticators.__setitem__, 'LOGIN')
        class _:

          @staticmethod
          @untwisted.each
          def challengeResponse():
            yield

            yield username

            yield 'notPassword'

        ctx.authenticate(None).addCallback(untwisted.partial(ok, False)).addErrback(untwisted.partial(ok, True))

  reactor.connectTCP(host, 'imap', factory)

  return promise.promise()
