#!/usr/bin/env python

import base64
from mail.test import *
from untwisted import dns, smtp, stun, tcp

expect(1)

response = stun.request('stun.telepathy.im')

@sdfg
def _():
  listen = tcp.listen('smtp')

  #@...
  @untwisted.identity(listen().then)
  def server(transport):
    class server(smtp.server):

      @untwisted.each
      def mail():
        ctx = yield

        class sample(smtp.server.mail):
          def sender(ctx, sender):
            pass

          def recipient(ctx, sender):
            pass

          def content(ctx, content):
            pass

        ctx = yield sample.__get__(ctx)()

        # QUIT
        yield smtp.server.mail.__get__(ctx)()

    qname, _ = transport.client

    qname = qname.split('.')
    qname.reverse()
    qname = '.'.join(qname) + '.in-addr.arpa'

    return promise.join(server(transport), dns.lookup(qname, dns.PTR).then(lambda actual: equal('mail.nottheoilrig.com.', actual.answer.ptrdname)))

  @untwisted.call
  @promise.resume
  def _():
    while True:
      ok(False, (yield listen()))

  connect = tcp.connect('mail.nottheoilrig.com', 'smtp')

  #@...
  @untwisted.identity(connect().then)
  class client(smtp.client):

    @untwisted.each
    def mail():
      ctx = yield

      ctx.transport.write(str(smtp.command('AUTH PLAIN', base64.b64encode('\0' + username + '\0' + password))))

      ctx.reply()

      class sample(smtp.client.mail):
        sender = iter(('test@example.com',)).next
        recipient = iter((response.then(lambda response: 'test@[{}]'.format(response.attribute[stun.MAPPED_ADDRESS].address)),)).next
        content = iter(('Expect',)).next

      yield sample.__get__(ctx)()

  return server
