#!/usr/bin/env python

import os
from mail.test import *
from untwisted import smtp, tcp

expect(1)

@sdfg
@promise.resume
def _():
  host = os.environ.get('HOST', 'mail.nottheoilrig.com')

  connect = tcp.connect(host, 'smtp')

  client = type.__call__(smtp.client, (yield connect()))

  yield client.reply()

  yield client.ehlo()

  mail = type.__call__(client.mail)

  yield mail.mail('alice@example.com')

  try:
    ok(False, (yield mail.rcpt('bob@example.com')))

  except smtp.reply:
    ok(True)

  #return ...
  raise StopIteration(client.quit())
