#!/usr/bin/env python

import base64, socket
from mail.test import *
from mail.test import rfc4871
from qwer import *
from twisted.internet import protocol
from twisted.web import http
from untwisted import rfc5321, smtp, tcp

expect(3)

# Cache our domain
domain = socket.getfqdn()

@sdfg
def _():

  @untwisted.call
  class factory(protocol.ClientFactory):
    class protocol(http.HTTPClient):
      def connectionMade(ctx):
        ctx.sendCommand('GET', '/test@' + domain)

        ctx.sendHeader('Authorization', 'Basic ' + base64.b64encode(username + ':' + password))

        ctx.endHeaders()

      def handleResponse(ctx, body):
        listen = tcp.listen('smtp')

        #@...
        @untwisted.identity(listen().then)
        class server(smtp.server):

          @untwisted.each
          def mail():
            ctx = yield

            class sample(smtp.server.mail):
              sender = staticmethod(untwisted.each(lambda: (yield equal(body + '@nottheoilrig.com', str((yield))))))
              recipient = staticmethod(untwisted.each(lambda: (yield equal('test@' + domain, str((yield))))))

              @staticmethod
              @untwisted.each
              def content():
                content = yield

                yield ok(qwer(rfc5321.timeStampLine, 'DKIM-Signature:', rfc4871.tagList, '\r\n', rfc5321.timeStampLine, '\r\n'.join((
                  'Date: Fri, 13 Feb 2009 15:31:30 -0800 \(PST\)',
                  'From: {}@nottheoilrig\.com'.format(body),
                  'Message-ID: 1234567890@example\.com',
                  '',
                  'Expect'))).match(content), content)

            ctx = yield sample.__get__(ctx)()

            # QUIT
            yield smtp.server.mail.__get__(ctx)()

        @untwisted.call
        @promise.resume
        def _():
          while True:
            ok(False, (yield listen()))

        connect = tcp.connect('mail.nottheoilrig.com', 'smtp')

        #@...
        @untwisted.identity(connect().then)
        class client(smtp.client):

          @untwisted.each
          def mail():
            ctx = yield

            ctx.transport.write(str(smtp.command('AUTH PLAIN', base64.b64encode('\0' + username + '\0' + password))))

            ctx.reply()

            class sample(smtp.client.mail):
              sender = iter(('test@example.com',)).next
              recipient = iter(('test@' + domain,)).next
              content = iter(('\r\n'.join((
                'Date: Fri, 13 Feb 2009 15:31:30 -0800 (PST)',
                'From: notTest@example.com',
                'Message-ID: 1234567890@example.com',
                '',
                'Expect')),)).next

            yield sample.__get__(ctx)()

  reactor.connectTCP('mail.nottheoilrig.com', 'http', factory)

  return promise.promise()
