#!/usr/bin/env python

# Lookup DNS SRV record

from mail.test import *
from untwisted import dns

expect(2)

@sdfg
@promise.resume
def _():
  answer = (yield dns.lookup('nottheoilrig.com', dns.NS)).answer

  expect(2 * len(answer))

  for answer in answer:
    response = yield dns.lookup('_sip._udp.nottheoilrig.com', dns.SRV, server=answer.nsdname)

    ok(response.aa)

    for answer in response.answer:
      equal('mail.nottheoilrig.com.', answer.target)
