#!/usr/bin/env python

from mail.test import *
from mail.test import tls
from untwisted import smtp, tcp

expect(1)

@sdfg
@promise.resume
def _():
  connect = tcp.connect('mail.nottheoilrig.com', 'submission')

  client = type.__call__(smtp.client, (yield connect()))

  yield client.reply()

  yield client.ehlo()

  client.transport.write(str(smtp.command('STARTTLS')))

  yield client.reply()

  yield tls.startTls(client.transport)

  mail = type.__call__(client.mail)

  yield mail.mail('alice@example.com')

  try:
    ok(False, (yield mail.rcpt('bob@example.com')))

  except smtp.reply:
    ok(True)

  #return ...
  raise StopIteration(client.quit())
