#!/usr/bin/env python

# Connect to SMTP server on submission port and verify authentication fails
# with wrong password

import base64, os
from mail.test import *
from untwisted import smtp, tcp

expect(1)

host = os.environ.get('LC_HOST', 'mail.nottheoilrig.com')

@sdfg
@promise.resume
def _():
  connect = tcp.connect(host, 'submission')

  client = type.__call__(smtp.client, (yield connect()))

  yield client.reply()

  yield client.ehlo()

  client.transport.write(str(smtp.command('AUTH PLAIN', base64.b64encode('\0' + username + '\0notPassword'))))

  try:
    ok(False, (yield client.reply()))

  except smtp.reply:
    ok(True)

  #return ...
  raise StopIteration(client.quit())
